#!/bin/bash

clear

# Colors
RED='\033[0;31m'
GRN='\033[0;32m'
CYN='\033[0;36m'
YEL='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YEL}"
cat << "EOF"
 /$$      /$$                 /$$                                                  /$$   /$$
| $$$    /$$$                | $$                                                 | $$  / $$
| $$$$  /$$$$  /$$$$$$   /$$$$$$$  /$$$$$$  /$$$$$$  /$$   /$$ /$$$$$$$   /$$$$$$ |  $$/ $$/
| $$ $$/$$ $$ /$$__  $$ /$$__  $$ /$$__  $$|____  $$| $$  | $$| $$__  $$ /$$__  $$ \  $$$$/ 
| $$  $$$| $$| $$  \__/| $$  | $$| $$  \__/ /$$$$$$$| $$  | $$| $$  \ $$| $$  \ $$  >$$  $$ 
| $$\  $ | $$| $$      | $$  | $$| $$      /$$__  $$| $$  | $$| $$  | $$| $$  | $$ /$$/\  $$
| $$ \/  | $$| $$      |  $$$$$$$| $$     |  $$$$$$$|  $$$$$$$| $$  | $$|  $$$$$$/| $$  \ $$
|__/     |__/|__/       \_______/|__/      \_______/ \____  $$|__/  |__/ \______/ |__/  |__/
                                                     /$$  | $$                              
                                                    |  $$$$$$/                              
                                                     \______/                                    
EOF
echo -e "${NC}"

echo -ne "${GRN}🔥 Please Subscribe \n"
for i in {1..3}; do
  echo -ne "${CYN}Subscribing To MrdraynoX"
  for dot in {1..3}; do
    echo -n "."
    sleep 0.3
  done
  echo -ne "\r                     \r"
done
echo -e "${GRN} Thanks for Subscribing! If Not Do It Rn${NC}\n"
sleep 1
#!/bin/bash


# Install fastfetch
echo "Installing fastfetch..."
wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.32.1/fastfetch-linux-amd64.deb && apt install ./fastfetch-linux-amd64.deb

# Run Neofetch to display system information
echo "Running fastfetch..."
fastfetch

echo "All tasks completed successfully!"
